version: '3.8'

services:
  url-shortener-1:
    build:
      context: .
      dockerfile: url-shortener-server/Dockerfile
    command: --node-id 0 --http-addr "0.0.0.0:8080" --raft-rpc-addr "0.0.0.0:21001" --data-dir "/data"
    ports:
      - "8080:8080"  # HTTP API
      - "21001:21001"  # Raft RPC
    volumes:
      - url_shortener_1_data:/data
    networks:
      - url_shortener_network

  url-shortener-2:
    build:
      context: .
      dockerfile: url-shortener-server/Dockerfile
    command: --node-id 1 --http-addr "0.0.0.0:8080" --raft-rpc-addr "0.0.0.0:21002" --data-dir "/data"
    ports:
      - "8081:8080"  # HTTP API
      - "21002:21002"  # Raft RPC
    volumes:
      - url_shortener_2_data:/data
    networks:
      - url_shortener_network

  url-shortener-3:
    build:
      context: .
      dockerfile: url-shortener-server/Dockerfile
    command: --node-id 2 --http-addr "0.0.0.0:8080" --raft-rpc-addr "0.0.0.0:21003" --data-dir "/data"
    ports:
      - "8082:8080"  # HTTP API
      - "21003:21003"  # Raft RPC
    volumes:
      - url_shortener_3_data:/data
    networks:
      - url_shortener_network

  init-cluster:
    build:
      context: .
      dockerfile: url-shortener-server/Dockerfile
    depends_on:
      - url-shortener-1
      - url-shortener-2
      - url-shortener-3
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 5 &&
      curl -X POST 'http://url-shortener-1:8080/cluster/init' &&
      curl -X POST 'http://url-shortener-1:8080/cluster/add-learner' -H 'Content-Type: application/json' -d '[2, \"url-shortener-2:21002\"]' &&
      curl -X POST 'http://url-shortener-1:8080/cluster/add-learner' -H 'Content-Type: application/json' -d '[3, \"url-shortener-3:21003\"]' &&
      curl -X POST 'http://url-shortener-1:8080/cluster/change-membership' -H 'Content-Type: application/json' -d '[1, 2, 3]'"
    networks:
      - url_shortener_network

volumes:
  url_shortener_1_data:
  url_shortener_2_data:
  url_shortener_3_data:

networks:
  url_shortener_network:
    driver: bridge 